/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package stringserializer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Former extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6697471597188933103L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Former\",\"namespace\":\"stringserializer\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"stream\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Former> ENCODER =
      new BinaryMessageEncoder<Former>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Former> DECODER =
      new BinaryMessageDecoder<Former>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Former> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Former> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Former> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Former>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Former to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Former from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Former instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Former fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence Name;
  private java.lang.CharSequence stream;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Former() {}

  /**
   * All-args constructor.
   * @param Name The new value for Name
   * @param stream The new value for stream
   */
  public Former(java.lang.CharSequence Name, java.lang.CharSequence stream) {
    this.Name = Name;
    this.stream = stream;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Name;
    case 1: return stream;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Name = (java.lang.CharSequence)value$; break;
    case 1: stream = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }


  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'stream' field.
   * @return The value of the 'stream' field.
   */
  public java.lang.CharSequence getStream() {
    return stream;
  }


  /**
   * Sets the value of the 'stream' field.
   * @param value the value to set.
   */
  public void setStream(java.lang.CharSequence value) {
    this.stream = value;
  }

  /**
   * Creates a new Former RecordBuilder.
   * @return A new Former RecordBuilder
   */
  public static stringserializer.Former.Builder newBuilder() {
    return new stringserializer.Former.Builder();
  }

  /**
   * Creates a new Former RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Former RecordBuilder
   */
  public static stringserializer.Former.Builder newBuilder(stringserializer.Former.Builder other) {
    if (other == null) {
      return new stringserializer.Former.Builder();
    } else {
      return new stringserializer.Former.Builder(other);
    }
  }

  /**
   * Creates a new Former RecordBuilder by copying an existing Former instance.
   * @param other The existing instance to copy.
   * @return A new Former RecordBuilder
   */
  public static stringserializer.Former.Builder newBuilder(stringserializer.Former other) {
    if (other == null) {
      return new stringserializer.Former.Builder();
    } else {
      return new stringserializer.Former.Builder(other);
    }
  }

  /**
   * RecordBuilder for Former instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Former>
    implements org.apache.avro.data.RecordBuilder<Former> {

    private java.lang.CharSequence Name;
    private java.lang.CharSequence stream;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(stringserializer.Former.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.stream)) {
        this.stream = data().deepCopy(fields()[1].schema(), other.stream);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Former instance
     * @param other The existing instance to copy.
     */
    private Builder(stringserializer.Former other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stream)) {
        this.stream = data().deepCopy(fields()[1].schema(), other.stream);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }


    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public stringserializer.Former.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public stringserializer.Former.Builder clearName() {
      Name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'stream' field.
      * @return The value.
      */
    public java.lang.CharSequence getStream() {
      return stream;
    }


    /**
      * Sets the value of the 'stream' field.
      * @param value The value of 'stream'.
      * @return This builder.
      */
    public stringserializer.Former.Builder setStream(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.stream = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'stream' field has been set.
      * @return True if the 'stream' field has been set, false otherwise.
      */
    public boolean hasStream() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'stream' field.
      * @return This builder.
      */
    public stringserializer.Former.Builder clearStream() {
      stream = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Former build() {
      try {
        Former record = new Former();
        record.Name = fieldSetFlags()[0] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.stream = fieldSetFlags()[1] ? this.stream : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Former>
    WRITER$ = (org.apache.avro.io.DatumWriter<Former>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Former>
    READER$ = (org.apache.avro.io.DatumReader<Former>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.Name);

    out.writeString(this.stream);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Name = in.readString(this.Name instanceof Utf8 ? (Utf8)this.Name : null);

      this.stream = in.readString(this.stream instanceof Utf8 ? (Utf8)this.stream : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Name = in.readString(this.Name instanceof Utf8 ? (Utf8)this.Name : null);
          break;

        case 1:
          this.stream = in.readString(this.stream instanceof Utf8 ? (Utf8)this.stream : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










